from __future__ import annotations

import pytest

from app.features.introspection.parser import parse_postgres_ddl


def test_parse_postgres_ddl_extracts_tables_columns_and_constraints():
    sql_text = """
    CREATE TABLE public.users (
      id bigint GENERATED BY DEFAULT AS IDENTITY,
      email text NOT NULL,
      CONSTRAINT users_pkey PRIMARY KEY (id),
      CONSTRAINT users_email_key UNIQUE (email)
    );

    CREATE TABLE public.accounts (
      id bigint,
      user_id bigint NOT NULL
    );

    ALTER TABLE ONLY public.accounts
      ADD CONSTRAINT accounts_user_fk
      FOREIGN KEY (user_id) REFERENCES public.users(id)
      ON UPDATE RESTRICT ON DELETE CASCADE;
    """

    parsed = parse_postgres_ddl(sql_text)

    assert parsed.schema_names == ["public"]
    assert {(table.schema_name, table.table_name) for table in parsed.tables} == {
        ("public", "users"),
        ("public", "accounts"),
    }

    users_id = next(
        column
        for column in parsed.columns
        if column.schema_name == "public"
        and column.table_name == "users"
        and column.column_name == "id"
    )
    assert users_id.is_primary_key is True
    assert users_id.is_unique is True
    assert users_id.is_nullable is False
    assert users_id.column_default == "generated by default as identity"

    users_email = next(
        column
        for column in parsed.columns
        if column.schema_name == "public"
        and column.table_name == "users"
        and column.column_name == "email"
    )
    assert users_email.is_unique is True
    assert users_email.is_nullable is False

    assert len(parsed.foreign_keys) == 1
    relationship = parsed.foreign_keys[0]
    assert relationship.name == "accounts_user_fk"
    assert relationship.from_table == "accounts"
    assert relationship.from_column == "user_id"
    assert relationship.to_table == "users"
    assert relationship.to_column == "id"
    assert relationship.on_update_action == "RESTRICT"
    assert relationship.on_delete_action == "CASCADE"


def test_parse_postgres_ddl_handles_psql_copy_sections_and_user_defined_types():
    sql_text = r"""
    \connect my_database
    CREATE TABLE custom.orders (
      id uuid PRIMARY KEY,
      tags text[],
      status custom.order_status NOT NULL DEFAULT 'draft'
    );
    COPY custom.orders (id, status) FROM stdin;
    57a8a0f6-a2d0-4d80-8ef9-3f47a6f3a816	draft
    \.
    """

    parsed = parse_postgres_ddl(sql_text)

    assert parsed.schema_names == ["custom"]
    assert len(parsed.tables) == 1
    assert parsed.tables[0].schema_name == "custom"
    assert parsed.tables[0].table_name == "orders"

    status_column = next(column for column in parsed.columns if column.column_name == "status")
    assert status_column.data_type == "USER-DEFINED"
    assert status_column.udt_name == "order_status"
    assert status_column.column_default == "'draft'"

    tags_column = next(column for column in parsed.columns if column.column_name == "tags")
    assert tags_column.data_type == "text[]"


def test_parse_postgres_ddl_requires_create_table():
    with pytest.raises(ValueError, match="No CREATE TABLE"):
        parse_postgres_ddl("SELECT 1;")
